ekf_filter_odom:
  ros__parameters:
    use_sim_time: false
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    print_diagnostics: true

    # Frame settings
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # IMU input
    imu0: /imu/data
    imu0_queue_size: 50
    imu0_nodelay: true
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: false
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    

    # Wheel odometry input
    odom0: /wheel/odom
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_differential: false
    odom0_relative: false
    odom0_config: [false, false, false,
                  false, false, false,
                  true, false, false,
                  false, false, true,
                  false, false, false]

    transform_time_offset: 0.07
    transform_timeout: 0.5



    # State Order:
    # [position_x, position_y, position_z,
    #  orientation_roll, orientation_pitch, orientation_yaw,
    #  linear_velocity_x, linear_velocity_y, linear_velocity_z,
    #  angular_velocity_roll, angular_velocity_pitch, angular_velocity_yaw
    #  linear_acceleration_x, linear_acceleration_y, linear_acceleration_z]
