# meters, kilograms
# Temporary placeholder values (0.50)

wheelchair:
  base_length: 0.820   # The front-to-back length of the wheelchair frame (x-axis)
  base_width: 0.640    # The left-to-right width of the wheelchair frame  (y-axis)
  base_height: 0.260   # The vertical thickness of the chassis box (z-axis)
  base_z: 0.171

  wheel_radius: 0.171  # for odometry calculations
  wheel_width: 0.070   # The thickness of the wheel

# x: forward-backward from base center
# y: left-right
# z: upward, downward
sensors:
  realsense_xyz: [0.32, 0.00, 0.47]   # The position of the camera center relative to base_link
  lidar_xyz: [0.360, 0.28, 0.43]
  imu_xyz: [0.325, 0.0, 0.342]
